version: '2'

networks:
  main:

services:
  app:
    image: ahannigan/meteor:latest
    volumes:
      - ./app:/app
    networks:
     - main
    ports:
      - "3000"
    environment:
      - MONGO_URL=mongodb://mongo/myapp
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    networks:
     - main
